# Generated by Django 4.0.3 on 2023-03-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0008_automobilevo_import_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrecord',
            name='sale_price_currency',
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='sale_price',
            field=models.CharField(max_length=14),
        ),
    ]
