# Generated by Django 4.0.3 on 2023-03-09 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_rename_employee_id_technician_employee_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='purchased_from_dealership',
        ),
    ]
