# Generated by Django 4.0.3 on 2023-03-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0015_alter_appointment_vin_alter_automobilevo_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_vip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
